### ISSUE TITLE
2.0 documentation structure

### ISSUE THREAD

**Issue by BTCparadigm** [zkSNACKs/WasabiDoc2#2]
Would be nice to hear what kind of ideas we have for information structure and categories in 2.0 docs website?

In [1.0 docs](https://docs.wasabiwallet.io/) we basicly have 6 categories (Why Wasabi, Using Wasabi...), from which the last one (GitHub) is just a hyperlink to the repository.

Keep in mind, one of the main goals of this new 2.0 documentation is to be simpler than it's predecessor.

**Comment by nopara73** [comment]
How about making it a GitHub wiki on the WalletWasabi repository?

**Comment by BTCparadigm** [comment]
That sounds simple but can it be easily mirrored to the docs website?
For example 1.0 docs looks weird in Github repo.

**Comment by yahiheb** [comment]
something like https://github.com/libbitcoin/libbitcoin-system/wiki?

**Comment by nopara73** [comment]
The url can point there

**Comment by BTCparadigm** [comment]
So no separate website for docs? Just a github wiki?

**Comment by BTCparadigm** [comment]
I was thinking about something like this as a general structure
https://github.com/zkSNACKs/WalletWasabi/discussions/6740#discussioncomment-1840029

**Comment by nopara73** [comment]
> So no separate website for docs? Just a github wiki?

That is the idea. What are the cons?

**Comment by BTCparadigm** [comment]
I'm ok with having and not having a website but afaik the marketing team wants to have one.

Ping @CAnorbo

**Comment by nopara73** [comment]
I like this idea more and more. Although I was never a fan of GitHub wiki, it feels to me like a sh*load of future maintenance costs can be saved if we do this.

**Comment by nopara73** [comment]
Another pro. I wasn't able to contribute to the docs properly, because whenever I tried I had to chime through code and figure out how these things even work.

**Comment by BTCparadigm** [comment]
> sh*load of future maintenance costs can be saved if we do this.

True. I'm not too familiar with GitHub wiki but for what I read it seemed really simple. 
I'll paste this discussion to the marketing team's Slack channel to get their thoughts, because it seems most of them are not following this repo and I don't wanna wait too long to get this resolved.

**Comment by CAnorbo** [comment]
> I'm ok with having and not having a website but afaik the marketing team wants to have one.
> 
> Ping @CAnorbo

It's up to you guys. Everything on the GitHub, so if you want go forward with the GitHub Wiki, it's good for me.

**Comment by CAnorbo** [comment]
Imo the VuePress is more transparent for me and we can modify the design but on GitHub Wiki we have the GitHub Design.
The visual is not bother me, but for me the GitHub Wiki's structure with lot of content could be confusing.

**Comment by BTCparadigm** [comment]
Ping @yahiheb, @MarnixCroes, @ernez84, @MaxHillebrand
Any thoughts?
GitHub wiki or a website for docs 2.0?

**Comment by ernez84** [comment]
Why not both? I prefer more website if thinking big picture if both are too heavy load to keep updated.

**Comment by nopara73** [comment]
### GitHub Wiki
- less maintenance burden
- easier to contribute

### Standalone Website
- more customizable
- better look
- better search

Since the docs are miscellaneous material, I'd prefer if we wouldn't create more work for us or for whoever will maintain these in the future, so I'd prefer GitHub Wiki. As more and more people join a project, entropy does its job, everything gets more and more chaotic and look at us right now. I'd prefer if we'd fight against entropy rather than being the source of it.

Of course @BTCparadigm and @MarnixCroes are the current owner of the docs, so whatever their decision will be, we'll respect that.

**Comment by BTCparadigm** [comment]
Actually, @yahiheb is the main dictator of this repo :D Me and @MarnixCroes will just try to help out with the content and I take the resposibility to kick peoples ass to get this done or if something goes wrong.

@nopara73 that's a good brakedown of the tradeoffs. Still waiting for others to voice their opinions

**Comment by yahiheb** [comment]
> Actually, @yahiheb is the main dictator of this repo

Lol I think I am the dictator of this repo only, but to have a GitHub wiki on the WalletWasabi repository is a decision we should all contribute to.

I am 50-50 on this, I see the pros of each approach, but I know from experience that having a good search helps a lot when dealing with any support request.
